# Generated by Django 5.2.17 on 2026-10-02 19:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        db_index=True, default="default_user", max_length=100
                    ),
                ),
                (
                    "day_number",
                    models.IntegerField(
                        blank=True,
                        help_text="Curriculum day (1-100) linked to this note",
                        null=True,
                    ),
                ),
                (
                    "topic_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. spark_joins, sql_window",
                        max_length=100,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField(help_text="Markdown note content")),
                (
                    "category",
                    models.CharField(
                        default="General",
                        help_text="Python, SQL, Spark, Kafka, Airflow, etc.",
                        max_length=100,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("is_pinned", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Academic Note",
                "verbose_name_plural": "Academic Notes",
                "ordering": ["-is_pinned", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="AcademicProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        db_index=True,
                        default="default_user",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "completed_days",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of completed day numbers [1, 2, ...]",
                    ),
                ),
                (
                    "day_status",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Per day progress status { '1': { 'learned': true, 'mcq': 100 } }",
                    ),
                ),
                (
                    "quiz_scores",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Quiz attempts and high scores per day/topic",
                    ),
                ),
                (
                    "coding_submissions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Solved coding/SQL exercises",
                    ),
                ),
                (
                    "saved_cheat_sheets",
                    models.JSONField(
                        blank=True, default=list, help_text="Saved cheat sheet day IDs"
                    ),
                ),
                (
                    "bookmarks",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Bookmarked lessons and interview questions",
                    ),
                ),
                (
                    "revision_items",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Spaced repetition revision items",
                    ),
                ),
                (
                    "capstone_progress",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Completed milestones for capstone project",
                    ),
                ),
                ("streak_count", models.IntegerField(default=1)),
                ("last_active_date", models.DateField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Academic Progress",
                "verbose_name_plural": "Academic Progress Records",
            },
        ),
        migrations.CreateModel(
            name="SQLQueryHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        db_index=True, default="default_user", max_length=100
                    ),
                ),
                ("query", models.TextField()),
                ("status", models.CharField(default="success", max_length=20)),
                ("execution_time_ms", models.FloatField(default=0.0)),
                ("row_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "SQL Query History",
                "verbose_name_plural": "SQL Query History",
                "ordering": ["-created_at"],
            },
        ),
    ]
