# Generated by Django 5.2.17 on 2026-10-01 17:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BirthdayConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creator_name",
                    models.CharField(default="Saketh (Saki)", max_length=100),
                ),
                (
                    "recipient_name",
                    models.CharField(default="Akku (Akshatha)", max_length=100),
                ),
                (
                    "greeting_title",
                    models.CharField(default="Happy Birthday, Akku! ❤️", max_length=255),
                ),
                (
                    "love_letter",
                    models.TextField(
                        default="Happy Birthday to the most special person in my life. Every little moment, message, and memory we have shared means the world to me. I made this little world just for you."
                    ),
                ),
                (
                    "surprise_message",
                    models.TextField(
                        default="You are my favorite journey, my dearest Akku. Every day with you is a gift. Happy Birthday!"
                    ),
                ),
                (
                    "birthday_date",
                    models.CharField(default="October 2", max_length=100),
                ),
                ("background_music_enabled", models.BooleanField(default=False)),
                ("theme", models.CharField(default="romantic_rose", max_length=50)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PersonalVocabulary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        help_text="Correct term (e.g. Akku, Saki, Saketh, Besant Nagar)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "misrecognitions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Misrecognized spellings to replace automatically",
                    ),
                ),
                ("category", models.CharField(default="name", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("times_used", models.PositiveIntegerField(default=1)),
            ],
            options={
                "verbose_name_plural": "Personal Vocabulary",
                "ordering": ["term"],
            },
        ),
        migrations.CreateModel(
            name="PersonalMemory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "memory_text",
                    models.TextField(
                        help_text="The extracted fact or memory statement about Akku"
                    ),
                ),
                (
                    "original_input",
                    models.TextField(
                        blank=True,
                        help_text="The original message spoken or typed by Saketh",
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("food_drinks", "Food & Drinks"),
                            ("likes_dislikes", "Likes & Dislikes"),
                            ("personal_preferences", "Personal Preferences"),
                            ("health_wellness", "Health & Wellness"),
                            ("habits_routines", "Habits & Daily Routines"),
                            ("important_dates", "Important Dates & Occasions"),
                            ("shared_experiences", "Shared Experiences & Incidents"),
                            ("music_entertainment", "Music & Entertainment"),
                            ("places_travel", "Places & Travel"),
                            ("family_friends", "Family & Friends"),
                            ("future_plans", "Future Plans"),
                            ("gifts_surprises", "Gifts & Surprises"),
                            ("other", "Other Memories"),
                        ],
                        default="personal_preferences",
                        max_length=50,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        help_text="Short topic (e.g. Ice Cream, Headache, Favorite Song)",
                        max_length=150,
                        null=True,
                    ),
                ),
                ("source", models.CharField(default="text", max_length=20)),
                ("confidence", models.FloatField(default=1.0)),
                ("event_date", models.CharField(blank=True, max_length=100, null=True)),
                ("conversation_timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="previous_versions",
                        to="memories.personalmemory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Personal Memories",
                "ordering": ["-conversation_timestamp"],
            },
        ),
    ]
