# Generated by Django 5.2.17 on 2026-10-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalmemory",
            name="user_id",
            field=models.CharField(
                db_index=True,
                default="default_user",
                help_text="User ID for isolation",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="birthdayconfig",
            name="birthday_date",
            field=models.CharField(default="October 20", max_length=100),
        ),
        migrations.AlterField(
            model_name="birthdayconfig",
            name="creator_name",
            field=models.CharField(default="Saki", max_length=100),
        ),
        migrations.AlterField(
            model_name="birthdayconfig",
            name="recipient_name",
            field=models.CharField(default="Akku", max_length=100),
        ),
    ]
