# Generated by Django 5.2.17 on 2026-10-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memories", "0002_personalmemory_user_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalmemory",
            name="content_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="SHA-256 content hash for deduplication",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="personalmemory",
            name="importance",
            field=models.FloatField(
                default=0.8, help_text="Importance score from 0.1 to 1.0"
            ),
        ),
        migrations.AddField(
            model_name="personalmemory",
            name="is_user_confirmed",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="personalmemory",
            name="source_reference",
            field=models.CharField(
                blank=True,
                help_text="e.g. Page 4, chat session, etc.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="personalmemory",
            name="source_type",
            field=models.CharField(
                db_index=True,
                default="user_memory",
                help_text="initial_pdf, user_memory, conversation, agent_extracted, manual_update",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="personalmemory",
            name="speaker",
            field=models.CharField(
                default="Akku",
                help_text="Speaker or subject: Akku, Saki, Both, or User",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="personalmemory",
            name="status",
            field=models.CharField(
                choices=[
                    ("current", "Current (Active)"),
                    ("historical", "Historical (Past / Superseded)"),
                    ("archived", "Archived"),
                ],
                db_index=True,
                default="current",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="personalmemory",
            name="summary",
            field=models.TextField(
                blank=True, help_text="Concise summary for semantic indexing", null=True
            ),
        ),
        migrations.AddField(
            model_name="personalmemory",
            name="version",
            field=models.PositiveIntegerField(
                default=1, help_text="Memory version number"
            ),
        ),
        migrations.AlterField(
            model_name="personalmemory",
            name="category",
            field=models.CharField(
                choices=[
                    ("relationship", "Relationship & Love Story"),
                    ("personal_preferences", "Personal Preferences"),
                    ("favorite", "Favorites"),
                    ("food_drinks", "Food & Drinks"),
                    ("places_travel", "Places & Travel"),
                    ("important_dates", "Important Dates & Occasions"),
                    ("shared_experiences", "Shared Experiences & Incidents"),
                    ("music_entertainment", "Music & Entertainment"),
                    ("likes_dislikes", "Likes & Dislikes"),
                    ("health_wellness", "Health & Wellness"),
                    ("habits_routines", "Habits & Daily Routines"),
                    ("family_friends", "Family & Friends"),
                    ("future_plans", "Future Plans & Promises"),
                    ("gifts_surprises", "Gifts & Surprises"),
                    ("education", "Education & College"),
                    ("career", "Career & Work"),
                    ("emotion", "Emotions & Feelings"),
                    ("movie", "Movies & Shows"),
                    ("other", "Other Memories"),
                ],
                default="personal_preferences",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="personalmemory",
            name="confidence",
            field=models.FloatField(
                default=1.0, help_text="Confidence score from 0.0 to 1.0"
            ),
        ),
        migrations.AlterField(
            model_name="personalmemory",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="personalmemory",
            name="source",
            field=models.CharField(default="text", max_length=50),
        ),
    ]
