# Generated by Django 5.2.17 on 2026-10-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memories", "0003_personalmemory_content_hash_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalmemory",
            name="is_visible",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="personalmemory",
            name="visibility",
            field=models.CharField(db_index=True, default="visible", max_length=20),
        ),
    ]
